{% set name = "asap" %}
{% set version = "3.13.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/asap3/asap3-{{ version }}.tar.gz
  sha256: 4f878ce3e77520e92eba9faea8ed4b1a9f4baca40c2a213339ec31284dd3a0d5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - numpy
    - pip
    - python
    - setuptools
  run:
    - ase
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - asap3

about:
  home: https://pypi.org/project/asap3
  license: LGPL-3.0-only
  license_file:
    - LICENSE
    - LICENSE.LESSER
  summary: ASAP is a calculator for doing large-scale molecular dynamics (MD) within the Atomic Simulation Environment.

  description: |
    ASAP (Atomic SimulAtion Program or As Soon As Possible) is a
    package for large-scale molecular dynamics within the Atomic
    Simulation Environment (ASE).  It implements a number of 'classical'
    potentials, most importantly the Effective Medium Theory, and also the
    mechanisms for domain-decomposition of the atoms.

  doc_url: https://wiki.fysik.dtu.dk/asap
  dev_url: https://gitlab.com/asap/asap

extra:
  recipe-maintainers:
    - Anthchirp
